package it.uniparthenope.fairwind.sdk.ui;

/**
 * Created by raffaelemontella on 07/05/16.
 */
public enum ViewDataType {
    UNKNOWN,
    POSITION,
    TIME,
    WPTINFO,
    HEADING,SPEED,BEARING,
    VMG,VMG2WPT,
    WIND_ANGLE,WIND_DIRECTION,WIND_SPEED,
    COG,SOG,
    COG_SOG,
    HEADING_SPEED,
    BEARING_VMG,

    WIND_ANGLE_SPEED,WIND_DIRECTION_SPEED,
    BEARING_VMG2WPT,
    SET_DRIFT,
    AIRTEMP,TWCHILL,HUMIDITY,AIR_PRESSURE,
    WATERTEMP,WATERSAILINITY,
    LIVEWELL,BAITWELL,

    ENGINE_RPM,ENGINE_COOLANT_TEMP,ENGINE_OIL_TEMP, ENGINE_COOLANT_PRESS,ENGINE_OIL_PRESS, ENGINE_WATER_TEMP,
    FUEL_TANK,WATER_TANK,TOTAL_FUEL_TANK;
}
